# Generated by Django 6.0.2 on 2026-02-25 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='Số phòng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Ảnh đại diện')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá mỗi đêm')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn trống')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại phòng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá dịch vụ')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('rating', models.IntegerField(verbose_name='Đánh giá (1-5)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Ngày nhận phòng')),
                ('check_out', models.DateField(verbose_name='Ngày trả phòng')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã xác nhận'), ('rejected', 'Từ chối')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room', verbose_name='Phòng')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roomtype', verbose_name='Loại phòng'),
        ),
    ]
