# Generated by Django 6.0.2 on 2026-03-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên địa điểm')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='Hình ảnh')),
                ('booking_count', models.IntegerField(default=0, verbose_name='Số chỗ ở')),
            ],
        ),
    ]
