# Generated by Django 6.0.2 on 2026-03-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(default='Hà Nội', max_length=255, verbose_name='Địa chỉ/Thành phố'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả phòng'),
        ),
    ]
