# Generated by Django 6.0.2 on 2026-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_destination_image_alter_room_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Đơn đặt phòng'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name_plural': 'Địa điểm thu hút'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Phòng'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Loại phòng'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.service', verbose_name='Dịch vụ đi kèm'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã xác nhận'), ('rejected', 'Từ chối'), ('completed', 'Đã trả phòng')], default='pending', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá mỗi đêm'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Số phòng'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá dịch vụ'),
        ),
    ]
