# Generated by Django 6.0.2 on 2026-06-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Đánh dấu để hiển thị địa điểm này ở phần địa điểm nổi bật.', verbose_name='Nổi bật'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Ảnh địa điểm'),
        ),
    ]
